"""empty message

Revision ID: 11c4ffa23e0d
Revises: 3fe89d362ceb
Create Date: 2021-04-11 18:01:53.892462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c4ffa23e0d'
down_revision = '3fe89d362ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tercera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('lastname', sa.String(length=250), nullable=False),
    sa.Column('age', sa.String(length=250), nullable=False),
    sa.Column('tercera', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tercera'], ['segunda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tercera')
    # ### end Alembic commands ###
