"""empty message

Revision ID: b67416ee6eb3
Revises: 11c4ffa23e0d
Create Date: 2021-04-11 18:04:17.592479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b67416ee6eb3'
down_revision = '11c4ffa23e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tercera', sa.Column('segunda', sa.Integer(), nullable=True))
    op.drop_constraint('tercera_ibfk_1', 'tercera', type_='foreignkey')
    op.create_foreign_key(None, 'tercera', 'segunda', ['segunda'], ['id'])
    op.drop_column('tercera', 'tercera')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tercera', sa.Column('tercera', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tercera', type_='foreignkey')
    op.create_foreign_key('tercera_ibfk_1', 'tercera', 'segunda', ['tercera'], ['id'])
    op.drop_column('tercera', 'segunda')
    # ### end Alembic commands ###
